In [69]:
import torch
from torch import nn
from torch.distributions.normal import Normal

In [257]:
mu = nn.Parameter(torch.ones(1, 5))

In [305]:
b = nn.Parameter(torch.zeros(1, 5))
b.expand_as(mu)
b = torch.exp(b)
b[:,0:2]=0.001
b

tensor([[0.0010, 0.0010, 1.0000, 1.0000, 1.0000]], grad_fn=<CopySlices>)

In [306]:
probs = Normal(mu, b)
probs

Normal(loc: torch.Size([1, 5]), scale: torch.Size([1, 5]))

In [353]:
probs.sample()

tensor([[0.9999, 1.0001, 0.0515, 1.6548, 2.1213]])

In [432]:
probs.log_prob(probs.sample())

tensor([[ 5.5514,  4.7116, -1.4198, -1.2944, -1.0087]], grad_fn=<SubBackward0>)

In [410]:
probs.entropy()

tensor([[-5.4888, -5.4888,  1.4189,  1.4189,  1.4189]], grad_fn=<AddBackward0>)

In [446]:
obs = torch.zeros((10,1,5,5))
obs[0] = torch.ones((1,5,5))
obs

tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0

In [7]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.param = nn.Parameter(torch.randn(1, 1))
        
    def forward(self, x):
        x = x * self.param
        return x

model = MyModel()
print(dict(model.named_parameters()))
# {'param': Parameter containing:
# tensor([[0.6077]], requires_grad=True)}

out = model(4)
print(out)
loss = out.mean()
print(loss)
loss.backward()

print(model.param.grad)
# tensor([[-1.3033]])

{'param': Parameter containing:
tensor([[0.5310]], requires_grad=True)}
tensor([[2.1238]], grad_fn=<MulBackward0>)
tensor(2.1238, grad_fn=<MeanBackward0>)
tensor([[4.]])
